// This file is auto-generated by frontend/scripts/generate-bridge-message-types.mjs.
// Do not edit manually.

type ValueOf<T> = T[keyof T]

export const BRIDGE_MESSAGE_TYPES = {
  GET_TOOLS: 'getTools',
  ADD_TOOL: 'addTool',
  UPDATE_TOOL: 'updateTool',
  DELETE_TOOLS: 'deleteTools',
  RUN_TOOL: 'runTool',
  RUN_TOOL_IN_TERMINAL: 'runToolInTerminal',
  OPEN_URL_TOOL: 'openUrlTool',
  STOP_RUN: 'stopRun',
  GET_RUNS: 'getRuns',
  BROWSE_PYTHON: 'browsePython',
  BROWSE_FILE: 'browseFile',
  GET_PYTHON_PACKAGES: 'getPythonPackages',
  INSTALL_PYTHON_PACKAGE: 'installPythonPackage',
  UNINSTALL_PYTHON_PACKAGE: 'uninstallPythonPackage',
  GET_TERMINALS: 'getTerminals',
  START_TERMINAL: 'startTerminal',
  TERMINAL_INPUT: 'terminalInput',
  TERMINAL_RESIZE: 'terminalResize',
  STOP_TERMINAL: 'stopTerminal',
  GET_APP_DEFAULTS: 'getAppDefaults',
  EXPORT_DIAGNOSTIC_BUNDLE: 'exportDiagnosticBundle',
  TOOLS: 'tools',
  RUN_STARTED: 'runStarted',
  LOG: 'log',
  RUN_STATUS: 'runStatus',
  RUNS: 'runs',
  PYTHON_SELECTED: 'pythonSelected',
  FILE_SELECTED: 'fileSelected',
  TOOL_ADDED: 'toolAdded',
  TOOL_UPDATED: 'toolUpdated',
  TOOLS_DELETED: 'toolsDeleted',
  PYTHON_PACKAGES: 'pythonPackages',
  PYTHON_PACKAGE_INSTALL_STATUS: 'pythonPackageInstallStatus',
  TERMINALS: 'terminals',
  TERMINAL_STARTED: 'terminalStarted',
  TERMINAL_OUTPUT: 'terminalOutput',
  TERMINAL_STATUS: 'terminalStatus',
  APP_DEFAULTS: 'appDefaults',
  DIAGNOSTIC_BUNDLE_EXPORTED: 'diagnosticBundleExported',
  ERROR: 'error',
} as const

export type BridgeMessageType = ValueOf<typeof BRIDGE_MESSAGE_TYPES>

export const LOG_CHANNELS = {
  STDOUT: 'stdout',
  STDERR: 'stderr',
} as const

export type LogChannel = ValueOf<typeof LOG_CHANNELS>
